### ISSUE TITLE
Move Cl.Debug initialization

### ISSUE THREAD

**Issue by vxsx** [aldryn/aldryn-boilerplate-standard#29]
This is what we have in base currently.
```js
if (window.Cl && window.Cl.Debug) {
       new Cl.Debug();
}
```

It makes sense to move initialization into cl.debug.js itself and then you don't have debug paths in base.js (and compressed file eventually), and it will still init when file is loaded in browser.

**Comment by FinalAngel** [comment]
@vxsx agreeing?

**Comment by vxsx** [comment]
@FinalAngel well, yes and no. I guess consistency wins.
